services:

  nginx:
    image: nginx-lab-nginx:alpine
    container_name: nginx-failover
    depends_on:
      - backend1
      - backend2
    ports:
      - "8097:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - failover-network

  backend1:
    build: ./backend1
    image: nginx-lab-failover-backend1
    container_name: failover-backend1
    networks:
      - failover-network

  backend2:
    build: ./backend2
    image: nginx-lab-failover-backend2
    container_name: failover-backend2
    networks:
      - failover-network

networks:
  failover-network:
    driver: bridge
