events {}

http {

    # Shared memory zone
    limit_req_zone $binary_remote_addr zone=client_limit:10m rate=2r/s;

    upstream backend {
        server backend:8080;
    }

    server {
        listen 80;

        location / {
            limit_req zone=client_limit;
            proxy_pass http://backend;
        }
    }
}
