events {}

http {

    upstream health_backends {
        server backend1:8080 max_fails=2 fail_timeout=10s;
        server backend2:8080 max_fails=2 fail_timeout=10s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://health_backends;
        }

        location /health {
            proxy_pass http://health_backends/health;
        }
    }
}
