events {}

http {

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=2r/s;

    upstream rate_backend {
        server backend:8080;
    }

    server {
        listen 80;

        location / {
            limit_req zone=api_limit burst=2 nodelay;
            limit_req_status 429;

            proxy_pass http://rate_backend;
        }
    }
}
