events {}

http {
    upstream rewrite_backend {
        server backend:8080;
    }

    server {
        listen 80;

        location /app/users {
            rewrite ^/app/users$ /users break;
            proxy_pass http://rewrite_backend;
        }

        location /app/orders {
            rewrite ^/app/orders$ /orders break;
            proxy_pass http://rewrite_backend;
        }
    }
}
