events {}

http {

    upstream least_connection_backends {
        least_conn;

        server backend1:8080;
        server backend2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://least_connection_backends;
        }
    }
}
