events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        location /flights {
            proxy_ssl_server_name on;
            proxy_ssl_name opensky-network.org;
            proxy_set_header Host opensky-network.org;

            proxy_pass https://opensky-network.org/api/states/all?lamin=-35&lomin=16&lamax=-22&lomax=33;
        }
    }
}
