events {}

http {

    server {
        listen 80;

        location / {
            add_header X-Lab-Host $host always;
            add_header X-Lab-URI $request_uri always;
            add_header X-Lab-Method $request_method always;
            add_header X-Lab-Client-IP $remote_addr always;
            add_header X-Lab-Server-IP $server_addr always;
            add_header X-Lab-Status $status always;

            proxy_set_header X-Lab-Host $host;
            proxy_set_header X-Lab-URI $request_uri;
            proxy_set_header X-Lab-Method $request_method;
            proxy_set_header X-Lab-Client-IP $remote_addr;

            proxy_pass http://backend:8080;
        }
    }
}
