events {}

http {

    upstream access_backend {
        server backend:8080;
    }

    server {
        listen 80;

        location / {

            allow 192.168.16.1;
            deny all;

            add_header X-Client-IP $remote_addr always;

            proxy_pass http://access_backend;
        }
    }
}
