events {}

http {
    upstream backup_test {
        server backend1:8080;
        server backend2:8080;
        server backup:8080 backup;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backup_test;
        }
    }
}
