events {}

http {

    resolver 192.168.65.7 valid=30s;

    server {

        listen 80;

        location /weather {

            proxy_ssl_server_name on;
            proxy_ssl_name api.open-meteo.com;

            proxy_set_header Host api.open-meteo.com;

            proxy_pass https://api.open-meteo.com/v1/forecast?latitude=-26.1&longitude=28.2&current=temperature_2m,wind_speed_10m;
        }
    }
}
