events {}

http {
    upstream ip_hash_backends {
        ip_hash;

        server backend1:8080;
        server backend2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ip_hash_backends;
        }
    }
}
