events {}

http {

    upstream application_pool {
        server backend-1:8080;
        server backend-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://application_pool;
        }
    }
}
