events {}

http {

    gzip on;
    gzip_types text/plain application/json;

    server {

        listen 80;

        location / {

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header X-NGINX-Module-Lab "active" always;
            add_header X-NGINX-Version $nginx_version always;

            proxy_pass http://backend:8080;
        }
    }
}
