events {}

http {

    upstream application1 {
        server app1:8080;
    }

    upstream application2 {
        server app2:8080;
    }

    upstream api_service {
        server api:8080;
    }

    server {
        listen 80;

        location /app1/ {
            proxy_pass http://application1/;
        }

        location /app2/ {
            proxy_pass http://application2/;
        }

        location /api/ {
            proxy_pass http://api_service/;
        }
    }
}
