events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        location /fx {
            proxy_ssl_server_name on;
            proxy_ssl_name open.er-api.com;
            proxy_set_header Host open.er-api.com;

            proxy_pass https://open.er-api.com/v6/latest/USD;
        }
    }
}
