events {}

http {

    upstream users_api {
        server users-api:8080;
    }

    upstream orders_api {
        server orders-api:8080;
    }

    upstream health_api {
        server health-api:8080;
    }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://users_api;
        }

        location /api/orders {
            proxy_pass http://orders_api;
        }

        location /api/health {
            proxy_pass http://health_api;
        }
    }
}
