events {}

http {

    upstream backend_pool {
        server backend-1:8080;
        server backend-2:8080;
        server backend-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_pool;
        }
    }
}
